In [1]:
import numpy as np

# Практическое задание

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

In [2]:
A = np.random.randint(0, 10, (4, 2))
B = np.random.randint(0, 10, (4, 2))

In [3]:
np.dot(A, B)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [4]:
A.dot(B)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [5]:
B.dot(A)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [6]:
A = np.random.randint(0, 10, (2, 5))
B = np.random.randint(0, 10, (5, 3))

In [7]:
A.dot(B)

array([[117, 174,  71],
       [170, 220, 124]])

In [8]:
A.dot(B).shape

(2, 3)

In [9]:
B.dot(A)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [10]:
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (3, 8))

In [11]:
A.dot(B)

array([[ 68,  39, 147,  68,  77,  49, 158,  90],
       [ 70,  36, 105,  70,  64,  56, 139,  45],
       [ 70,  42, 159,  70,  88,  56, 169,  99],
       [ 52,  20,  62,  52,  14,  14,  84,  24],
       [ 18,  19, 104,  18,  57,  21,  81,  87],
       [  6,   8,  61,   6,  24,   0,  39,  57],
       [ 54,  32, 121,  54,  66,  42, 129,  75],
       [ 44,  25, 133,  44,  43,   7, 114, 102]])

In [12]:
A.dot(B).shape

(8, 8)

In [13]:
B.dot(A)

array([[115, 142, 183],
       [183, 267, 183],
       [131, 196, 221]])

In [14]:
B.dot(A).shape

(3, 3)

In [15]:
A = np.random.randint(0, 10, (4, 4))
B = np.random.randint(0, 10, (4, 4))

In [16]:
A.dot(B)

array([[ 91, 104,  99,  45],
       [ 50,  40,  18,  22],
       [ 64, 101,  81,  35],
       [ 89,  76,  54,  37]])

In [17]:
B.dot(A)

array([[ 34,  88, 150,  41],
       [ 34,  44,  65,  37],
       [ 25,  95, 136,  39],
       [ 40,  38,  63,  35]])

In [18]:
A.dot(B).shape

(4, 4)

In [19]:
A.dot(B).shape == B.dot(A).shape

True

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [20]:
A = np.array([[1, -2], [3, 0]])

In [21]:
B = np.array([[4, -1], [0, 5]])

In [22]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [23]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

In [24]:
B.dot(A)

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [25]:
A = np.array([[1, 7], [3, -6]])

In [26]:
B = np.array([[0, 5], [2, -1]])

In [27]:
C = np.array([[2, -4], [1, 1]])

In [28]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [29]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [30]:
At = A.T

In [31]:
A.dot(At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [32]:
At.dot(A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [33]:
def multiplication_matrix (A, B):
    a = 0 # элемент новой матрицы
    t = [] # строка новой матрицы
    m = [] # итоговая матрица
    if A.shape[1] != B.shape[0]:
        print("Нельзя перемножить матрицы. Кол-во столбцов 1-ой не соответствует кол-ву строк 2-ой.")
    else:
        for i in range(0, A.shape[0]):
            for j in range(0, B.shape[1]):
                for z in range(0, A.shape[1]):
                    a = a + A[i, z] * B[z, j]
                    t.append(a)
                    a = 0
                m.append(t)
                t = []
            return m

In [34]:
A = np.random.randint(0, 10, (2, 5))
B = np.random.randint(0, 10, (5, 3))

In [35]:
multiplication_matrix (A, B)

[[6, 12, 64, 10, 10], [42, 4, 72, 2, 40], [24, 12, 40, 12, 5]]